"""Progress tracking, generated from content/roster.yaml + the pages that exist.

Two generated outputs (never edit them by hand; `make progress` rewrites them):
  * the block between the progress markers in README.md   - the summary
  * content/README.md                                      - the per-instruction checklist
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .content import Content
from .models import CATEGORY_LABELS, Category, RosterEntry

START = "<!-- progress:start -->"
END = "<!-- progress:end -->"


@dataclass
class Row:
    entry: RosterEntry
    status: str  # "todo" | "draft" | "reviewed"


@dataclass
class Progress:
    rows: list[Row]
    articles: list[tuple[str, str, str]]  # (slug, title, status)
    sdm_revision: str

    @property
    def total(self) -> int:
        return len(self.rows)

    def count(self, *statuses: str) -> int:
        return sum(r.status in statuses for r in self.rows)

    @property
    def documented(self) -> int:
        return self.count("draft", "reviewed")


def compute(content: Content) -> Progress:
    rows = []
    for entry in content.roster.instructions:
        page = content.instructions.get(entry.slug)
        rows.append(Row(entry, page.status.value if page else "todo"))
    articles = [(a.slug, a.title, a.status.value) for a in content.articles.values()]
    return Progress(rows, articles, content.roster.sdm_revision)


def _pct(n: int, d: int) -> str:
    return f"{(100 * n / d):.0f}%" if d else "0%"


def render_summary(p: Progress) -> str:
    lines = [
        f"**Instructions documented: {p.documented} / {p.total} ({_pct(p.documented, p.total)})**"
        f" · reviewed: {p.count('reviewed')} · draft: {p.count('draft')}"
        f" · articles: {len(p.articles)}",
        "",
        "| Category | Documented | Total | Reviewed |",
        "|---|---:|---:|---:|",
    ]
    for cat in Category:
        rows = [r for r in p.rows if r.entry.category == cat]
        if not rows:
            continue
        done = sum(r.status != "todo" for r in rows)
        rev = sum(r.status == "reviewed" for r in rows)
        lines.append(f"| {CATEGORY_LABELS[cat]} | {done} | {len(rows)} | {rev} |")
    lines += [
        "",
        f"Scope roster against Intel SDM `{p.sdm_revision}`. Per-instruction checklist: "
        "[content/README.md](content/README.md). _Generated by `make progress`; do not edit._",
    ]
    return "\n".join(lines)


def render_checklist(p: Progress, content: Content) -> str:
    out = [
        "<!-- GENERATED by `make progress` from content/roster.yaml and the pages in this "
        "directory. Do not edit by hand. -->",
        "",
        "# Content progress",
        "",
        f"Roster against Intel SDM `{p.sdm_revision}`. "
        f"**{p.documented} / {p.total}** instruction pages written "
        f"({p.count('reviewed')} reviewed, {p.count('draft')} draft). "
        "`draft` = written and checked against the SDM by an LLM; `reviewed` = a human has "
        "checked it. To add a page, follow [docs/CONTENT_GUIDE.md](../docs/CONTENT_GUIDE.md).",
        "",
    ]
    for cat in Category:
        rows = [r for r in p.rows if r.entry.category == cat]
        if not rows:
            continue
        done = sum(r.status != "todo" for r in rows)
        out += [f"## {CATEGORY_LABELS[cat]} ({done}/{len(rows)})", ""]
        for r in rows:
            e = r.entry
            if r.status == "todo":
                out.append(f"- [ ] `{e.mnemonic}` (`{e.slug}`) — todo")
            else:
                out.append(f"- [x] [`{e.mnemonic}`](instructions/{e.slug}.md) — {r.status}")
        out.append("")
    out += ["## Articles", ""]
    out += [f"- [{t}](articles/{s}.md) — {st}" for s, t, st in p.articles] or ["_None yet._"]
    out += ["", "## Deferred (decision pending, not counted above)", ""]
    out += [
        f"- {', '.join(f'`{m}`' for m in d.mnemonics)} — {d.reason}"
        for d in content.roster.deferred
    ]
    out += ["", "## Excluded (out of scope)", ""]
    for x in content.roster.excluded:
        note = f" — {x.note}" if x.note else ""
        out.append(f"- {', '.join(f'`{m}`' for m in x.mnemonics)} — `{x.reason}`{note}")
    return "\n".join(out) + "\n"


def splice_block(text: str, block: str) -> str:
    try:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
    except ValueError:
        raise ValueError(f"README.md must contain {START} and {END} markers") from None
    return f"{head}{START}\n{block}\n{END}{tail}"


def sync(content: Content, root: Path, *, write: bool) -> list[Path]:
    """Return the generated files that are out of date; rewrite them when write=True."""
    p = compute(content)
    stale: list[Path] = []
    targets = {
        root / "README.md": lambda cur: splice_block(cur, render_summary(p)),
        root / "content" / "README.md": lambda _cur: render_checklist(p, content),
    }
    for path, render in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        wanted = render(current)
        if wanted != current:
            stale.append(path)
            if write:
                path.write_text(wanted, encoding="utf-8")
    return stale
